- name: "Step 1a. Create groups for App"
  group:
    name: "{{ item.group }}"
    system: yes
    state: present
  with_items:
    - "{{ jboss_app_users }}"
  become: yes

- name: "Step 1b. Create users for App"
  user:
    name: "{{ item.user }}"
    comment: "{{ item.user }} user"
    group: "{{ item.group }}"
    home: "{{ item.user_home }}"
    shell: "/bin/bash"
  become: yes
  with_items:
    - "{{ jboss_app_users }}"

- name: "Step 2. Install JDK 1.8"
  become: true
  yum: name={{ item }} state=present
  with_items:
   - unzip
   - "{{ java_pkg_name }}"

- name: "Step 3. Update .bash_profile"
  template:
    src: .bash_profile.j2
    dest: "{{ item.user_home }}/.bash_profile"
    owner: "{{ item.user }}"
    group: "{{ item.group }}"
  register: bashrc_uploaded
  become: true
  with_items:
    - "{{ jboss_app_users }}"

