---
- name: "Step 20. Copy service systemd unit file"
  template:
    owner: "{{ jboss_app_users.user }}"
    group: "{{ jboss_app_users.group }}"
    src: jboss-as-standalone.service.j2
    dest: "/etc/systemd/system/{{ jboss_eap_instance_service_name }}.service"
    mode: "0750"
  register: conf_service

# Reloading systemd. Should be executed here and not as a handler.
- name: "Step 21. Reload systemd"
  when: conf_service.changed
  command: systemctl daemon-reload

- name: "Step 22. Ensure JBoss EAP is running"
  service:
    name: "{{ jboss_eap_instance_service_name }}"
    state: started
    enabled: yes
  become: yes

- name: "Step 23. Install War file"
  shell:  "./bin/jboss-cli.sh \
      --controller={{ jboss_bind_address }}:{{ jboss_eap_instance_management_http_port|int +  jboss_eap_instance_port_offset|int}} \
      --connect \
      --user={{ jboss_management_users[0].user }} \
      --password={{ jboss_management_users[0].password }} \
      --command='deploy {{ item }}'"
  args:
    chdir: "{{ target_dir }}"
  when: jboss_eap_war_files|length > 0
  with_items: "{{ jboss_eap_war_files }}"
  tags:
  - install_war_file