---

#### Setup users and install required packages
- include: 00__prereqs.yml
  become: true

#### Gracefully stop and remove the current instance.
- include: 01__graceful_removal.yml
  become: true
  when: jboss_eap_force_remove|bool

#### Copy JBoss EAP installation binaries
- include: 02__copy_and_unpack.yml
  become: true

#### Check configuration changes in a clone directory
- include: 03__configure.yml
  become: true

#### Create Service Account
- include: 04__register_service.yml
  become: true

#- name: debug
#  debug: var=hostvars[inventory_hostname]